name: Analytics Feature
description: Track implementation of analytics features
title: "[Analytics] "
labels: ["analytics", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Track the implementation of analytics features
  - type: input
    id: feature-name
    attributes:
      label: Analytics Feature
      description: Name of the analytics feature
      placeholder: "e.g., Player Performance Tracking"
    validations:
      required: true
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of analytics is this?
      options:
        - Visualization
        - Data Collection
        - Performance Metrics
        - Player Statistics
        - Game Analysis
        - Custom Reports
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: What data needs to be collected/analyzed?
  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
      description: Technical details and considerations
  - type: checkboxes
    id: components
    attributes:
      label: Required Components
      options:
        - label: Data Collection Service
        - label: Analytics Processing
        - label: Visualization Component
        - label: Admin Dashboard Integration
        - label: Export Functionality
  - type: textarea
    id: database-changes
    attributes:
      label: Database Changes
      description: Required changes to Firebase/Firestore schema