name: Bug Report
description: Create a report to help us improve
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Report a bug or issue in the application
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: Clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Production
        - Development
        - Test
        - Shopify Embed
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any relevant logs or error messages
      render: shell
  - type: checkboxes
    id: impact
    attributes:
      label: Impact Areas
      options:
        - label: Game Functionality
        - label: Analytics
        - label: Authentication
        - label: Admin Features
        - label: Shopify Integration