name: Sync Repositories

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Sync local changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull --rebase origin main
        git push origin main